name: Trigger Notes Update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger notes update
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" \
          https://api.github.com/repos/username/personal-software-learning-notes/dispatches \
          -d '{"event_type":"update_from_leetcode"}'
